version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password123  # Parola pentru utilizatorul sa
    ports:
      - "1433:1433"  # Exponerea portului SQL Server
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
